######################################################################
# Automatically generated by qmake (2.01a) dom dez 2 10:50:26 2012
######################################################################

TEMPLATE = app
TARGET = Alcantara
DEPENDPATH += . include src
INCLUDEPATH += . include
CONFIG += qdbus
# Input
HEADERS += include/Alcantara.h include/singleInstance.h
FORMS += alcantara.ui
SOURCES += main.cpp src/Alcantara.cpp src/singleInstance.cpp
CONFIG += qdbus
