######################################################################
# Automatically generated by qmake (2.01a) sáb nov 3 17:56:44 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += . include src
INCLUDEPATH += . include

# Input
HEADERS += include/Alcantara.h
FORMS += alcantara.ui
SOURCES += main.cpp src/Alcantara.cpp
